/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIDOMMozJrdFotaManager;

[scriptable, uuid(b442e6a7-78b1-404f-9b56-7c6e34639b6e)]
interface nsIDOMMozNavigatorJrdFota: nsISupports
{
  readonly attribute nsIDOMMozJrdFotaManager mozJrdFota;
};
